### ISSUE TITLE
Crash when join server

### ISSUE THREAD

**Issue by Rozbiynk** [TeamMidnightDust/VisualOverhaul#48] opened 2023-07-25 12:22 UTC
https://mclo.gs/cJ8naah

**Comment by Rozbiynk** [comment] 2023-08-04 20:02
bump

**Comment by netcore10** [comment] 2023-10-23 14:10
same here https://mclo.gs/TCnHS9P

**Comment by Motschen** [comment] 2024-02-23 20:39
Duplicate of #36

**Closed by Motschen** 2024-02-23 20:39 UTC
